AppBundle\Entity\Repo:
    type: entity
    table: repo
    repositoryClass: AppBundle\Repository\RepoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        github_id:
            type: integer
        name:
            type: string
            length: 255
            unique: false
            nullable: false
        url:
            type: string
            length: 255
            unique: true
            nullable: false
        created_at:
            type: datetime
            unique: false
            nullable: false
        last_push_date:
            type: datetime
            unique: false
            nullable: false
        description:
            type: text
            nullable: true
        stars:
            type: integer
            unique: false
            nullable: false
    lifecycleCallbacks: {  }
